#include "main.h"
/**
 * _isalpha - checks for alphabetic character.
 * @c: int value generated by standard library ctype.h
 * Description: check and Returns 1 if c is a letter,
 * Return: int value
 **/
int _isalpha(int c)
{
if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
return (1);
else
return (0);
}
